[project]
name = "03fastapidetails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "â€œfistasolutionsâ€", email = "fistasolutions@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
]

[project.scripts]
03fastapidetails = "03fastapidetails:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
